manager_db:
  image: cloudopting/manager-db
  #build: ./database
  restart: always
  hostname: db
  container_name: manager_db
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=1qaz2wsx
  # Expose ports only for debug
  ports:
    - "5432:5432"

manager_jcr:
  #image: rootlogin/jackrabbit
  build: ./jackrabbit
  restart: always
  hostname: jcr
  container_name: manager_jcr
  #environment:
  ports:
    - "8082:8080"

manager:
  #image: cloudopting/manager
  build: ./manager
  restart: always
  hostname: manager
  container_name: manager
  links:
    - manager_db:db
    - manager_jcr:jcr
    # - crane-commander:crane
  environment:
    - JAVA_OPTS=-Dspring.profiles.active=prod
  ports:
    - "8080:8080"
